# .github/workflows/changelog.yml
name: Weekly Changelog

on:
  schedule:
    - cron: '0 6 * * MON' # Every Monday at 06:00 UTC
  workflow_dispatch:
    inputs:
      force:
        description: 'Force update even if week entry already exists'
        type: boolean
        default: false

jobs:
  create_changelog:
    runs-on: ubuntu-latest
    
    # IMPORTANT: This permission is required to commit the changelog file
    permissions:
      contents: write 

    steps:
      - name: Generate Weekly Changelog
        uses: fridzema/ai-weekly-changelog-action@0.0.15
        with:
          # Required: Your OpenRouter API key
          openrouter_api_key: ${{ secrets.OPENROUTER_API_KEY }}

          # Optional inputs with their defaults:
          # days_back: 7
          # model: 'openai/gpt-4o-mini'
          # language: 'English'
          # extended: false
          force: ${{ github.event.inputs.force || false }}

