name: Weekly Update
on:
  workflow_dispatch: # Add this to enable manual triggering
  schedule:
    - cron: '0 16 * * 5' # Runs every Friday at 18:00 CET (16:00 UTC)
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
      - name: Configure Git
        run: |
          git config --global user.name "Vítězslav Dvořák"
          git config --global user.email "info@vitexsoftware.cz"
      - name: Install dependencies
        run: npm install @octokit/rest
      - name: Fetch commits and compile update
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
        run: node compile-update.js
